stages:
  - build_docker

build:docker:
  image: docker:latest
  stage: build_docker
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - "docker build --pull -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME ."
    - "docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
